Add datepicker
masonitedoors/MDL pull request #165
Opened 2021-03-31 19:47 UTC by rhedman32

Before submitting a pull request, please make sure the following is done:

1. Make sure your updates are reflected in both the React and HTML side of MDL.
2. If you've fixed a bug or added code that should be tested, add tests!
3. Make sure the test suite passes (`npm test`).

2021-04-02 17:54 UTC, willyrk1 requested changes
It won't be much but these should also be done in Typescript as we've been doing lately.

Also remember to update \MDL\packages\external-ui-react\src\index.js or else your new component won't get exported by the library at all.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/react.js
> +				calendarContainer={MyContainer}
IDK what happened to spacing here. Looks like a mix of spaces and tabs Just a quick ctrl-left-arrow and ctrl-right-arrow in VS Code would probably fix it.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/react.js
> +    <div>
I don't think this `<div>` is really needed, is it? I'd try getting rid of it.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/react.js
> +const Datepicker = ({ className, ...props }) => {
The Datepicker className is prop is unused. If you meant to just pass all props into the 3rd party DatePicker, you'll want to remove className here and just do `const Datepicker = props =>`

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/react.stories.js
> +			<>
More crazy spacing here.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/react.stories.js
> +		const handleChange = date => setDate(date);
This handleChange doesn't seem to serve any purpose. You could just use `onChange={setDate}` below.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/react.stories.js
> +// import classNames from 'classnames/bind'
These commented lines can be removed. Also, the entire stories.module.scss file can be deleted.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/style.module.scss
> +	:global(.react-datepicker__header) {
There's lots of opportunity for tightening this whole file up with SASS. E.g., change this to just `&__header {` and move it into the `:global(.react-datepicker) {` block

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/style.module.scss
> +	:global(.react-datepicker__day-names) {
Tightening can be done to another level here. If above is changed to `&__day {`, then this one can be moved under that one and then shortened to `&-names {`.

2021-04-02 17:54 UTC, willyrk1 commented on components/Datepicker/style.module.scss
> +	:global(.react-datepicker__day--keyboard-selected),
commas still work in SASS so this could be just `&--keyboard-selected, &--selected {` under `&__day` above.

2021-04-02 17:54 UTC, willyrk1 commented on package.json
> +    "react-modern-calendar-datepicker": "^3.1.6"
If we've rallied around one 3rd party datepicker, let's remove the other one.

2021-04-09 19:00 UTC, tarikhamilton approved these changes

2021-04-09 19:05 UTC, merged