Table WIP
masonitedoors/MDL pull request #75
Opened 2019-08-23 18:27 UTC by tarikhamilton

Just making this visible.

2019-10-22 19:27 UTC, josephfusco commented
@tarikhamilton

I like how you have this currently setup where the more advanced table features are opt-in via props. Looks good so far. 👍

2020-09-30 19:58 UTC, jdashley27 approved these changes

2020-10-02 18:27 UTC, jdashley27 requested changes
Hello Tarik,

Overall, looks pretty good. The team (Bill, Rob, Ian, Joe, & Simon), had felt we may want to pull out the Popover functionality to be separate from the base table, as the functionality pertains to MPrice, and not to other applications. It was acknowledged it is there as a prop, but this may be better as having the functionality itself passed in as a prop, rather than having it in the base table. Please reach out to the group if you feel this should be a discussion, as we want to get your insight and feedback.

Thanks!

2020-10-05 18:13 UTC, tarikhamilton commented
> Hello Tarik,
> 
> Overall, looks pretty good. The team (Bill, Rob, Ian, Joe, & Simon), had felt we may want to pull out the Popover functionality to be separate from the base table, as the functionality pertains to MPrice, and not to other applications. It was acknowledged it is there as a prop, but this may be better as having the functionality itself passed in as a prop, rather than having it in the base table. Please reach out to the group if you feel this should be a discussion, as we want to get your insight and feedback.
> 
> Thanks!

The BulkEditPopover was created during MPrice, but I don't see this as an MPrice specific feature. It is essentially an API for selecting row/column data. We would be excluding that as a feature overall from the table. Is there a specific concern or scenario you could outline?

I can see an argument for writing it as a hook, to separate the BulkEdit concerns from the table for the purpose of organizing, but I don't see any advantages of taking it out.

Taking it out would mean...
- It would require special instructions or multiple libraries to use (complication)
- Rewriting complex logic that already exists and is tested in a production environment (fragmented code, duplicated efforts)
- If we stored the feature elsewhere, and imported to enable it, there'd be no bundle size benefit or difference (no end-user benefit)

But keeping it means almost nothing. In fact, it doesn't work out of the box because it just provides you an interface to use it, rather than it trying to make it magically work when the data to build out the tables can vary so much.

2020-10-16 15:37 UTC, josephfusco approved these changes

2020-10-20 19:15 UTC, merged